// src/routes/privacy/+page.svelte
<script lang="ts">
	import Metadata from '$lib/components/Metadata.svelte';
	import { githubIssuesUrl, projectNameStylized } from '$lib/metadata';
</script>

<Metadata
	title="Privacy Policy"
	description="Privacy policy for {projectNameStylized}"
	path="privacy"
/>

<main class="flex items-center justify-center p-4 sm:p-8">
	<article class="prose">
		<div class="divider" />
		<h1 class="my-0 text-center">Privacy Policy</h1>
		<div class="divider" />

		<p>
			This is the privacy policy for {projectNameStylized}.
			<br />
			Last updated on July 22, 2023.
		</p>

		<ul>
			<li>
				<p>
					<strong>Information We Collect</strong>
				</p>
				<p>On this website, we do not collect personal information from our visitors.</p>
			</li>

			<li>
				<p>
					<strong>First-party Cookies</strong>
				</p>
				<p>
					We save your application theme preference in <code>localStorage.theme</code> with a value
					of <code>light</code> or <code>dark</code> when you explicitly click on the
					<strong>Change Theme</strong> switch present in the footer.
				</p>
			</li>

			<li>
				<p>
					<strong>Server Provider</strong>
				</p>
				<p>
					This website is hosted by <a href="https://bunny.net/" target="_blank">Bunny.net</a>
					, an EU based company, which may collect some data to provide its services. To learn more about
					the data collected by Bunny.net, you can read their{' '}
					<a href="https://bunny.net/privacy" target="_blank">privacy policy</a>
					.
				</p>
			</li>

			<li>
				<p>
					<strong>Server Logs</strong>
				</p>
				<p>
					Our host, <a href="https://bunny.net/" target="_blank">Bunny.net</a>, provides us with
					<a href="https://docs.bunny.net/docs/cdn-log-format" target="_blank">server logs</a> that
					contain information about requests made to this website. Every IP address present in the
					logs is automatically anonymized to <code>0.0.0.0</code> to prevent storing personal data.
				</p>
			</li>

			<li>
				<p>
					<strong>External Websites</strong>
				</p>
				<p>
					This website may contain links to external websites not operated by us and thus with
					different privacy policies. We recommend you to review the privacy policy of any website
					you may visit.
				</p>
			</li>

			<li>
				<p><strong>Contact Information</strong></p>
				<p>
					You can contact the website owner, Edoardo Scibona, on{' '}
					<a href={githubIssuesUrl} target="_blank">Github</a> or by{' '}
					<a href="mailto:info@jsdocs.io">email</a>.
				</p>
			</li>
		</ul>

		<div class="divider" />
	</article>
</main>

// A_OLD/src/pages/privacy.tsx
import NextHead from 'next/head';
import { A } from '../components/common/A';
import { Layout } from '../components/common/Layout';

export default function PrivacyPolicyPage() {
    const pageTitle = 'Privacy Policy - VideoSpeedup.com';
    const pageDescription = 'Privacy policy for VideoSpeedup.com';

    return (
        <>
            <NextHead>
                <title>{pageTitle}</title>
                <meta name="description" content={pageDescription} />

                <meta property="og:title" content={pageTitle} />
                <meta property="og:description" content={pageDescription} />
                <meta
                    property="og:url"
                    content="https://www.videospeedup.com/privacy"
                />

                <meta property="twitter:title" content={pageTitle} />
                <meta
                    property="twitter:description"
                    content={pageDescription}
                />
            </NextHead>

            <Layout>
                <article className="space-y-12">
                    <IntroSection />
                    <FirstPartySection />
                    <HostingSection />
                    <LinksToExternalWebsitesSection />
                    <ContactInformationSection />
                </article>
            </Layout>
        </>
    );
}

function IntroSection() {
    return (
        <section>
            <h1>Privacy Policy</h1>

            <p>This page contains the privacy policy for VideoSpeedup.com.</p>

            <p>The privacy policy was last updated on July 3, 2023.</p>
        </section>
    );
}

function FirstPartySection() {
    return (
        <section>
            <h2>First Party</h2>

            <p>
                On VideoSpeedup.com we do not directly collect personal data
                from our visitors.
            </p>
        </section>
    );
}

function HostingSection() {
    return (
        <section>
            <h2>Hosting</h2>

            <p>
                VideoSpeedup.com is hosted on{' '}
                <A href="https://vercel.com/">Vercel</A>, which may collect some
                data to provide its hosting services.
            </p>

            <p>
                To learn more about the data collected by Vercel, you can visit
                their{' '}
                <A href="https://vercel.com/legal/privacy-policy">
                    privacy policy
                </A>{' '}
                page.
            </p>
        </section>
    );
}

function LinksToExternalWebsitesSection() {
    return (
        <section>
            <h2>Links to External Websites</h2>

            <p>
                VideoSpeedup.com may contain links to external websites not
                operated by us and with different privacy policies.
            </p>

            <p>
                We recommend you to review the privacy policy of any website you
                may visit.
            </p>
        </section>
    );
}

function ContactInformationSection() {
    return (
        <section>
            <h2>Contact Information</h2>

            <p>
                You can reach us by email at{' '}
                <A href="mailto:info@videospeedup.com">info@videospeedup.com</A>
                .
            </p>
        </section>
    );
}
