// src/components/common/Footer.tsx
import { A } from './A';
import { Link } from './Link';

export function Footer() {
    return (
        <footer className="p-5 bg-gray-100 border-t border-gray-300 dark:bg-gray-900 dark:border-gray-700 md:flex md:items-center md:justify-between">
            <p className="mt-0">
                <Link href="/">
                    <span className="font-bold text-gray-900 hover:underline dark:text-gray-100">
                        VideoSpeedup.com
                    </span>
                </Link>{' '}
                created by{' '}
                <A href="https://github.com/velut">Edoardo Scibona</A>
            </p>

            <ul className="mt-4 space-y-1 md:mt-0 sm:flex sm:space-x-4 sm:space-y-0">
                <li>
                    <Link href="/privacy">Privacy Policy</Link>
                </li>

                <li>
                    <A href="https://github.com/velut/videospeedup.com/issues">
                        Report an Issue
                    </A>
                </li>
            </ul>
        </footer>
    );
}

// src/lib/components/Footer.svelte
<script lang="ts">
	import FastForwardIcon from '$lib/components/FastForwardIcon.svelte';
	import ThemeSwitch from '$lib/components/ThemeSwitch.svelte';
	import {
		githubCommitShort,
		githubCommitUrl,
		githubUrl,
		projectNameStylized
	} from '$lib/metadata';
</script>

<footer class="footer bg-base-200 p-8 text-base text-base-content">
	<div>
		<a href="/" class="link-hover link flex items-center gap-2 text-lg font-bold">
			<FastForwardIcon class="h-5 w-5" />
			{projectNameStylized}
		</a>
		<p>
			Created by <a
				href="https://www.edoardoscibona.com"
				target="_blank"
				class="link-hover link font-bold">Edoardo Scibona</a
			>
		</p>
		<p class="text-sm">
			Commit: <a href={githubCommitUrl} target="_blank" class="link-hover link">
				{githubCommitShort}
			</a>
		</p>
	</div>

	<div>
		<span class="footer-title opacity-80">Links</span>
		<a href="/" class="link-hover link">Homepage</a>
		<a href={githubUrl} target="_blank" class="link-hover link">GitHub Project</a>
	</div>

	<div>
		<span class="footer-title opacity-80">Legal</span>
		<a href="/privacy/" class="link-hover link">Privacy Policy</a>
		<a href="/licenses/" class="link-hover link">Software Licenses</a>
	</div>

	<div>
		<span class="footer-title opacity-80">Theme</span>
		<ThemeSwitch />
	</div>
</footer>
